name: Windows Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Log
        id: log
        run: |
          LAST_TAG=`git tag --sort=-taggerdate | head -1`
          CURR_TAG=${{ github.event.after }}
          LOG=$(git log --pretty=format:'* %h: %s' $LAST_TAG..$CURR_TAG)
          LOG="${LOG//'%'/'%25'}"
          LOG="${LOG//$'\n'/'%0A'}"
          LOG="${LOG//$'\r'/'%0D'}"
          echo "::set-output name=log::$LOG"
          echo "::set-output name=last::$LAST_TAG"
          echo "::set-output name=curr::$CURR_TAG"

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Automated Release by GitHub Action CI
            [Changes](${{ github.event.repository.url }}/compare/${{ steps.log.outputs.last }}..${{ github.ref }}):
            ${{ steps.log.outputs.log }}
          draft: true
          prerelease: false

  build:
    needs: create_release
    name: Build Release Assets
    runs-on: windows-latest
    env:
      RUSTFLAGS: -Ctarget-feature=+crt-static

    strategy:
      fail-fast: false
      matrix:
        edition:
          - target: x86_64-pc-windows-msvc
            name: x64
          - target: i686-pc-windows-msvc
            name: x86

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.edition.target }}
          toolchain: stable-${{ matrix.edition.target }}
          default: true
          override: true

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.edition.target }}-cargo-${{ hashFiles('**/recipe.json') }}

      - name: Build
        run: cargo build --target ${{ matrix.edition.target }} --release

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: target/${{ matrix.edition.target }}/release/genshin-gacha-exporter.exe
          asset_name: genshin-gacha-exporter-${{ matrix.edition.name }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

  publish:
    name: Publish GitHub Release
    needs:
      - create_release
      - build

    runs-on: ubuntu-latest
    steps:
      - name: publish
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.create_release.outputs.id }}